### ISSUE TITLE
citations

### ISSUE THREAD

**Issue by KatJK** [govex/performance-management-getting-started#2]
Do we need to cite statements like these, or do we think our examples throughout the guide are evidence enough? 

"Until recently, governments made decisions largely based on instinct, anecdotal evidence, and politics. They lacked the time and resources needed to fully review the outcomes of various programs. However, the public sector is shifting toward governing with data thanks to improvements in technology, data collection, and the rise of performance management programs that emphasize the benefits of data-informed decision making. Forward-thinking governments are optimizing the power of data to create greater efficiency and better results for residents."

**Comment by technickle** [comment]
I don't think we need to do formal (footnoted) citations, but if we want to hyperlink to other resources which back up our statements, or provide examples, sure!
